# Generated by Django 4.2.7 on 2023-11-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=202)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=202)),
                ('message', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=202)),
                ('phone', models.CharField(max_length=202)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=202)),
            ],
        ),
    ]
