# Generated by Django 4.2.7 on 2023-11-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='body',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='title',
        ),
    ]
