# Generated by Django 4.2.7 on 2023-11-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=202)),
                ('title', models.CharField(max_length=202)),
                ('image', models.ImageField(upload_to='about/')),
                ('description', models.TextField()),
                ('linkedin', models.CharField(max_length=202)),
                ('instagram', models.CharField(max_length=202)),
                ('github', models.CharField(max_length=202)),
                ('telegram', models.CharField(max_length=202)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
